controller_joint_names: ['leftfinger_joint', 'rotating_joint', 'shoulder_joint', 'arms_joint', 'rightlink_joint', 'leftlink_joint', 'rightgear_joint', 'rightfinger_joint', 'leftgear_joint', 'leftfinger_joint', ]
